openapi: 3.0.3
info:
  title: Ping API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /ping:
    get:
      responses:
        '200':
          description: Réponse OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
